### PR TITLE
const Function

### PR DESCRIPTION
**Pull request by aeslaughter**

### CODE REVIEW

**Comment by aeslaughter** [comment]
This will fail because there isn't a MOOSE submodule, it will need to be merged in good faith.

**Comment by jessecarterMOOSE** [comment]
@aeslaughter understood but why then did this fail by Exodiff? I would have thought the wrong const-ness would have been a compilation error. It's also possible that my app has gotten a bit stale.

**Comment by aeslaughter** [comment]
Adding the const to the methods in this PR means that the non-const versions in the base class, which return 0, are the ones being called.

If the override keyword is added, there would be a compiler error. I will do that.

**Comment by aeslaughter** [comment]
@jessecarterMOOSE You need to re-activate this to test again. Thanks.

**Comment by jessecarterMOOSE** [comment]
@aeslaughter  Any idea why the testing doesn't happen automatically?

**Comment by aeslaughter** [comment]
@jessecarterMOOSE I must be listed as a collaborator for the tests to run automatically. 

This is ready to merge, all the necessary parts are in place within MOOSE.

**Pull request merged**
