### PR TITLE
Regold tests using periodic bcs and/or AMR with hanging-nodes

### PR DESCRIPTION
**Pull request by lindsayad**
Refs libMesh/libmesh#1986

### CODE REVIEW

**Comment by jessecarterMOOSE** [comment]
Thanks @lindsayad. I'll take a look at this when I'm in tomorrow. Not sure I follow the discussion on the referenced thread. What has changed in my solutions?

**Comment by lindsayad** [comment]
So the way we applied constraints for periodic BCs and hanging nodes in the past was by doing some fairly clever manipulation of the linear solve. The problem with this strategy was that if you ever approximated the Jacobian using finite differences (e.g. when doing PJFNK), you essentially ended up with a singular operator. We avoid this now by explicitly writing a non-linear residual for the constrained dof. Now the non-linear solve (through PETSc or whatever) computes the value of the constrained dof for us, rather than us computing the dof post-solve.

The effects on your simulation results (and everyone else's) are quite small at least from an outsider's perspective. All the exodiffing variables have magnitudes in the 10^-10 range. Here are the exact exodiffs:
```
kernels/recombination.recombination:   --------- Time step 1, 0.0000000e+00 ~ 0.0000000e+00, rel diff:  0.00000e+00 ---------
kernels/recombination.recombination: Nodal variables:
kernels/recombination.recombination:   --------- Time step 2, 1.0000000e-01 ~ 1.0000000e-01, rel diff:  0.00000e+00 ---------
kernels/recombination.recombination: Nodal variables:
kernels/recombination.recombination:    v  rel diff: -7.9664253e-10 ~ -7.9651444e-10 = 1.60786e-04 (node 3)
kernels/recombination.recombination:   --------- Time step 3, 2.0000000e-01 ~ 2.0000000e-01, rel diff:  0.00000e+00 ---------
kernels/recombination.recombination: Nodal variables:
kernels/recombination.recombination:    v  rel diff: -7.5047394e-10 ~ -7.5034520e-10 = 1.71547e-04 (node 3)
kernels/recombination.recombination:   --------- Time step 4, 3.0000000e-01 ~ 3.0000000e-01, rel diff:  0.00000e+00 ---------
kernels/recombination.recombination: Nodal variables:
kernels/recombination.recombination:    v  rel diff: -7.7076977e-10 ~ -7.7064286e-10 = 1.64654e-04 (node 3)
kernels/recombination.recombination: 
kernels/recombination.recombination: exodiff: Files are different
```
```
kernels/recombination.recombination_other_way: 
kernels/recombination.recombination_other_way: Sideset Distribution Factors:
kernels/recombination.recombination_other_way:   --------- Time step 1, 0.0000000e+00 ~ 0.0000000e+00, rel diff:  0.00000e+00 ---------
kernels/recombination.recombination_other_way: Nodal variables:
kernels/recombination.recombination_other_way:   --------- Time step 2, 1.0000000e-01 ~ 1.0000000e-01, rel diff:  0.00000e+00 ---------
kernels/recombination.recombination_other_way: Nodal variables:
kernels/recombination.recombination_other_way:    v  rel diff:  7.3306963e-11 ~ -2.8813958e-10 = 1.25441e+00 (node 422)
kernels/recombination.recombination_other_way:   --------- Time step 3, 2.0000000e-01 ~ 2.0000000e-01, rel diff:  0.00000e+00 ---------
kernels/recombination.recombination_other_way: Nodal variables:
kernels/recombination.recombination_other_way:    v  rel diff:  6.1956778e-11 ~ -1.1125765e-10 = 1.55688e+00 (node 1)
kernels/recombination.recombination_other_way:   --------- Time step 4, 3.0000000e-01 ~ 3.0000000e-01, rel diff:  0.00000e+00 ---------
kernels/recombination.recombination_other_way: Nodal variables:
kernels/recombination.recombination_other_way:    v  rel diff:  5.2064295e-11 ~ -1.0240938e-10 = 1.50839e+00 (node 1)
kernels/recombination.recombination_other_way: 
kernels/recombination.recombination_other_way: exodiff: Files are different
```
```
kernels/recombination.recombination_one_way: Sideset Distribution Factors:
kernels/recombination.recombination_one_way:   --------- Time step 1, 0.0000000e+00 ~ 0.0000000e+00, rel diff:  0.00000e+00 ---------
kernels/recombination.recombination_one_way: Nodal variables:
kernels/recombination.recombination_one_way:   --------- Time step 2, 1.0000000e-01 ~ 1.0000000e-01, rel diff:  0.00000e+00 ---------
kernels/recombination.recombination_one_way: Nodal variables:
kernels/recombination.recombination_one_way:    v  rel diff: -8.7227759e-10 ~ -8.7236213e-10 = 9.69121e-05 (node 419)
kernels/recombination.recombination_one_way:   --------- Time step 3, 2.0000000e-01 ~ 2.0000000e-01, rel diff:  0.00000e+00 ---------
kernels/recombination.recombination_one_way: Nodal variables:
kernels/recombination.recombination_one_way:    v  rel diff:  3.2557408e-09 ~  3.2560570e-09 = 9.71263e-05 (node 401)
kernels/recombination.recombination_one_way:   --------- Time step 4, 3.0000000e-01 ~ 3.0000000e-01, rel diff:  0.00000e+00 ---------
kernels/recombination.recombination_one_way: Nodal variables:
kernels/recombination.recombination_one_way:    v  rel diff:  3.2557408e-09 ~  3.2560570e-09 = 9.71263e-05 (node 401)
kernels/recombination.recombination_one_way: 
kernels/recombination.recombination_one_way: exodiff: Files are different
```
```
auxkernels/sink_map_aux.sink_map_aux: Nodal variables:
auxkernels/sink_map_aux.sink_map_aux: Element variables:
auxkernels/sink_map_aux.sink_map_aux:   --------- Time step 2, 1.0000000e-03 ~ 1.0000000e-03, rel diff:  0.00000e+00 ---------
auxkernels/sink_map_aux.sink_map_aux: Nodal variables:
auxkernels/sink_map_aux.sink_map_aux:    u  rel diff:  3.6175512e-10 ~  3.6172326e-10 = 8.80729e-05 (node 1971)
auxkernels/sink_map_aux.sink_map_aux: Element variables:
auxkernels/sink_map_aux.sink_map_aux:   --------- Time step 3, 2.0000000e-03 ~ 2.0000000e-03, rel diff:  0.00000e+00 ---------
auxkernels/sink_map_aux.sink_map_aux: Nodal variables:
auxkernels/sink_map_aux.sink_map_aux:    u  rel diff:  1.8753035e-10 ~  1.8752737e-10 = 1.59105e-05 (node 2678)
auxkernels/sink_map_aux.sink_map_aux: Element variables:
auxkernels/sink_map_aux.sink_map_aux: 
auxkernels/sink_map_aux.sink_map_aux: exodiff: Files are different
```

**Comment by jessecarterMOOSE** [comment]
👍 Looks good.

**Comment by lindsayad** [comment]
@jessecarterMOOSE Do you still have all the webhooks enabled for CIVET? We have not been able to fire a test on the devel branch, and I guess now that I look at it there was no testing done on this PR. You want to have a webhook that looks like the attached:

screen shot 2019-01-22 at 3 41 14 pm

**Comment by jessecarterMOOSE** [comment]
OK @lindsayad looks like the URL changed from http:// to https:// at some point. I made the change to my repo and re-pushed the payload and CIVET appeared to take it.

**Comment by lindsayad** [comment]
Awesome. Yes, I see it on our build page

**Pull request merged**
